### ISSUE TITLE
Prohibiting motion on HomeSw fails

### ISSUE THREAD

**Issue by JulianOrteil** [ponoor/step-series-universal-firmware#21]
@kanta My STEP400 running this universal firmware is not stopping when the home switch activates. I know the switch works because the motor homes just fine. Can you verify if you are getting this as well?

I'm using `python-step-series` and am pushing the `/run` command every 1/60th of a second. I'm using a config file with the prohibit motion checkbox checked.

**Comment by JulianOrteil** [comment]
Note: It does not matter if the motor homes before or after I see this behavior. I need to make sure this works otherwise the motor will lose its positioning and/or damage my components.

Thanks for the help in advance,
Jules

**Comment by kanta** [comment]
Hi @JulianOrteil , 
In default, the home switch won't stop the motor. You can change this setting with [`/setHomeSwMode`](https://ponoor.com/en/docs/step-series/osc-command-reference/home-and-limit-sensers/#sethomeswmode_intmotorid_boolsw_mode). This command is only executable when the motor is in a HiZ state. So could you try this sequence?
1. `/hardHiZ 1`
2. `/setHomeSwMode 1 0`

Also, this command only works for when the motor come in to the HOME from the outside. If you are sending `/run` commands repeatedly, the next `/run` will be executed even on the HOME. You can use [`/setProhibitMotionOnHomeSw`](https://ponoor.com/en/docs/step-series/osc-command-reference/alarm-settings/#setprohibitmotiononhomesw_intmotorid_boolenable) to prevent it.

This works fine for my end, tested with STEP400/universal firmware v1.2.1

**Comment by JulianOrteil** [comment]
@kanta Interesting! I'm still encountering this behavior even after doing your suggestion.

I'm doing all of the configurations via my [config file](https://github.com/ponoor/step-series-universal-firmware/files/9403332/config.txt). I'm only sending movement commands, not configurations from my code. The motor in question here is motor 2. Can you load it onto one of your test benches and see what you get?

Thanks!
Jules

**Comment by kanta** [comment]
@JulianOrteil Thanks for the config file, I made it to reproduce the issue.
I found the problem when boolean true values are overrode by false from the config file. I have fixed the bug with [this](https://github.com/ponoor/step-series-universal-firmware/commit/bc02d42ea8449614501598843fdc8b0b21347caf#diff-a54093b8a16480f9c3302c681cf4ff892df999bd941e9bcc27bcd01e87dc792b) commit and now the home switch works properly. 

Could you try the develop blanch? 

This problem was only happen when the settings were loaded from the config file. This is why I have not noticed...

**Comment by JulianOrteil** [comment]
@kanta Thanks for the quick fix! I can confirm your fix is working. We are still encountering some issues though. I've attached two videos for you to see the behavior we're getting.

The first video shows the switch activating and stopping the motor correctly. The second shows the motor stopping for a fraction of a second, and then continuing even with the switch active (the light on it is out).

https://user-images.githubusercontent.com/23083317/186429599-80056b74-c3ee-4758-a1cf-b32bd2c1eea9.mp4
https://user-images.githubusercontent.com/23083317/186429636-2935ccc8-9f26-43f2-a8e4-5db3f6a102a1.mp4

**Comment by kanta** [comment]
@JulianOrteil Thanks for the confirmation. 

Also thanks for the movies, I could reproduce the new problem. 
I am not completely sure what is happening there, but I think the following is possibly happening;

1. When the home switch is closed, the motor motion will be stopped by the motor driver chip in hardware level.
2. The MCU is polling the status of the drivers periodically and there is a some latency to get to know the switch situation.
3. If you send the `/run` command in exactly this timing, the MCU won't prevent the motion on the HOME switch, since the MCU haven't updated yet the switch state.

This is a less probable but possible. I added some extra code to make sure to stop the motion when the MCU get to know the home switch is closed. 
Could you try the [develop branch](https://github.com/ponoor/step-series-universal-firmware/tree/develop) again?

Thank you for the report!

**Comment by JulianOrteil** [comment]
@kanta I have not been able to reproduce this issue, so I believe it is safe to assume this is fixed. Thanks for your work!

**Comment by kanta** [comment]
Thank you for your test and report! Now these updates are released as v1.2.2.
